/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konyvtarmanager.view;

import javax.swing.JList;
import javax.swing.JOptionPane;
import konyvtarmanager.controller.KonyvtarManager;

/**
 *
 * @author n
 */
public class KolcsonzesDialog extends javax.swing.JPanel {
    private KonyvtarManager manager;
    private JList klista;
    
    /**
     * Creates new form KolcsonzesDialog2
     */
    public KolcsonzesDialog(KonyvtarManager manager, String ISBN) {
        initComponents();
        this.manager = manager;
        this.ISBNszam.setText(ISBN);
    }
    
    public KolcsonzesDialog(KonyvtarManager manager, JList kolcsonziLista, String kszam) {
        initComponents();
        this.manager = manager;
        this.klista = kolcsonziLista;
        this.konyvtarjegyszam.setText(kszam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        konyvtarjegyszam = new javax.swing.JTextField();
        ISBNszam = new javax.swing.JTextField();
        mentes_gomb = new javax.swing.JButton();

        konyvtarjegyszam.setToolTipText("Kérem a tag könyvtárjegy számát!");
        konyvtarjegyszam.setName(""); // NOI18N

        ISBNszam.setToolTipText("Kérem a könyv ISBN-számát!");

        mentes_gomb.setText("Mentés");
        mentes_gomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentes_gombMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ISBNszam, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(konyvtarjegyszam)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(mentes_gomb)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(konyvtarjegyszam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ISBNszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mentes_gomb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mentes_gombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentes_gombMouseClicked
        // TODO add your handling code here:
        String ISBN = ISBNszam.getText();
        String kjsz = konyvtarjegyszam.getText();
        Boolean siker = manager.kolcsonzes(ISBN, Integer.parseInt(kjsz), false);
        if(klista != null) {
            klista.setListData(manager.getKolcsonzesListaByTag(Integer.parseInt(kjsz)).toArray());
        }
        if(siker){
            JOptionPane.showMessageDialog(null, "Sikerült a kölcsönzés!", "Üzenet", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Büntetés vagy Zárolás miatt nem sikerült a kölcsönzés!", "Üzenet", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_mentes_gombMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNszam;
    private javax.swing.JTextField konyvtarjegyszam;
    private javax.swing.JButton mentes_gomb;
    // End of variables declaration//GEN-END:variables
}
