/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konyvtarmanager.view;

import javax.swing.JOptionPane;
import konyvtarmanager.controller.KonyvtarManager;

/**
 *
 * @author n
 */
public class TagFelveteleAblak extends javax.swing.JPanel {
    private KonyvtarManager manager;
    /**
     * Creates new form TagFelveteleAblak
     */
    public TagFelveteleAblak() {
        initComponents();
        this.manager = new KonyvtarManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nev_mezo = new javax.swing.JTextField();
        cim_mezo = new javax.swing.JTextField();
        mentes_gomb = new javax.swing.JButton();

        nev_mezo.setToolTipText("Kérem a tag nevét!");

        cim_mezo.setToolTipText("Kérem a tag címét!");

        mentes_gomb.setLabel("Mentés");
        mentes_gomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentes_gombMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cim_mezo)
                    .addComponent(nev_mezo))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(mentes_gomb)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nev_mezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cim_mezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mentes_gomb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mentes_gombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentes_gombMouseClicked
        // TODO add your handling code here:
        String nev = this.nev_mezo.getText();
        String cim = this.cim_mezo.getText();
        manager.ujTag(nev, cim);
        JOptionPane.showMessageDialog(null, "Sikerült a tag felvétele!", "Üzenet", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mentes_gombMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cim_mezo;
    private javax.swing.JButton mentes_gomb;
    private javax.swing.JTextField nev_mezo;
    // End of variables declaration//GEN-END:variables
}
